identifier: l637n4sdo6p319n6
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: portal
homeFolder: /Users/kemu/workspace/portal/portal
distFolder: dist/portal
outDir: /Users/kemu/workspace/portal/portal/dist/static
handle404: ''
allowErrorCollect: false
