name: deploy

on:
  issues:
    types: [opened, edited, deleted]
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.lock.txt'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
      - uses: actions/cache@v2
        with:
          key: 'assets-2022-04-01'
          path: ./portal/src/assets/
      - name: install deps
        working-directory: ./portal
        run: |
          npm install
      - name: collect article / prepare page, image, version, sitemap
        run: |
          pip install -r requirements.lock.txt
          python export_issues.py
          python create_img.py
          python create_pages.py
          python create_version.py
          python create_sitemap.py
          python create_rss.py
      - name: collect comments
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python export_comments.py
      - name: build
        working-directory: ./portal
        run: |
          npm run compodoc
          npm run ng build
          cp dist/portal/index.html dist/portal/404.html
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portal/dist/portal
      - name: deploy cloudflare
        uses: cloudflare/pages-action@v1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: portal
          directory: portal/dist/portal
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./portal/dist/portal/
