name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: hp/package-lock.json
      - name: install deps
        working-directory: ./hp
        run: |
          npm install
      - name: deploy
        working-directory: ./hp
        run: |
          npm run ng deploy --base-href=/kemu.site/
