name: deploy

on:
  issues:
    types: [opened, edited, deleted]
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.lock.txt'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
      - uses: actions/cache@v2
        with:
          key: 'assets-2022-05-28'
          path: ./portal/src/assets/comments/
      - name: install deps
        working-directory: ./portal
        run: |
          npm install
      - name: collect article / prepare page, image, version, sitemap
        run: |
          pip install -r requirements.lock.txt
          python export_issues.py
          python create_img.py
          python create_meta.py
          python create_version.py
          python create_sitemap.py
          python create_rss.py
      - name: collect comments
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python export_comments.py
      - name: build
        working-directory: ./portal
        run: |
          npm run compodoc
          npm run ng build -- --sourceMap=true |& tee -a $GITHUB_STEP_SUMMARY
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: 'production'
          sourcemaps: './portal/dist/portal/'
          set_commits: 'skip'
      - name: remove sourcemap
        run: |
          rm portal/dist/portal/*.map
      - name: SSG
        working-directory: ./portal
        run: |
          npm run scully |& tee -a $GITHUB_STEP_SUMMARY
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portal/dist/static/
          cname: portal.kemu.site
