name: lint

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
      - name: install deps
        working-directory: ./portal
        run: |
          npm install --legacy-peer-deps
      - name: lint
        working-directory: ./portal
        run: |
          npm run lint |& tee -a $GITHUB_STEP_SUMMARY
          exit ${PIPESTATUS[0]}
