name: lint & build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: hp/package-lock.json
      - name: install deps
        working-directory: ./hp
        run: |
          npm install
      - name: lint
        working-directory: ./hp
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: hp/package-lock.json
      - name: install deps
        working-directory: ./hp
        run: |
          npm install
      - name: build
        working-directory: ./hp
        run: |
          npm run build --prod --base-href=/kemu.site/
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hp/dist/hp/
