name: python_lint

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.lock.txt'
      - name: install deps
        run: |
          pip install -r rerequirements.lock.txt
      - name: lint
        run: |
          make lint
