name: translate

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.lock.txt'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: portal/package-lock.json
      - name: setup git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: install deps
        working-directory: ./portal
        run: |
          npm install --legacy-peer-deps
      - name: collect article / prepare page, image, version, sitemap
        run: |
          pip install -r requirements.lock.txt
          python export_issues.py
          python export_projects.py
          python create_img.py
          python create_meta.py
          python create_version.py
          python create_sitemap.py
          python create_rss.py
          python create_translate.py ${{ secrets.DEEPL_AUTH_KEY }}
      - name: fmt & push
        working-directory: ./portal
        run: |
          npm run fmt
          git add .
          git commit -m "add translate file"
          git push origin master
